---
title: "solutioins to the applied exercises in islr2 ch6"
author: "Wenwen Kong"
date: "9/2/2022"
output:
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 8
In this exercise, we will generate simulated data, and will then use this data to perform best subset selection.

  (a)
  Use the `rnorm()` function to generate a predictor $X$ of length $n = 100$, as well as a noise vector $\epsilon$ of length $n = 100$. 
  
  (b)
  Generate a response vector 



In Chapter 4, we used logistic regression to predict the probability of `default` using `income` and `balance` on the `Default` data set. We will now estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis. 

  (a) 
  Fit a logistic regression model that uses `income` and `balance` to predict `default`.
  
  (b)
  Generate a response vector $Y$ of length $n = 100$ according to the model 
  $Y = \beta_{0} + \beta_{1}X + \beta_{2}X^{2}+\beta_{3}X^{3}+ \epsilon$,
  where $\beta_{0}$, $\beta_{1}$, $\beta_{2}$, and $\beta_{3}$ are constants of your choice. 
  
  (c)
  Use the `regsubsets()` function to perform best subset selection in order to choose the best model containing the perdictors $X$, $X^{2}$, ..., $X^{10}$. What is the best model obtained according to $C_{p}$, $BIC$, and adjusted $R^{2}$? Show some plots to provide evidence for your answer, and report the coefficients of the best model obtained. Note you will need to use the `data.frame()` function to create a single data set containing both $X$ and $Y$. 
  
  (d)
  Repeat (c), using forward stepwise selection and also using backwards stepwise selection. How does your answer compare to the results in (c)?
  
  (e)
  Now fit a lasso model to the simulated data, again using $X$, $X^{2}$, ..., $X^{10}$ as predictors. Use cross-validation to select the optimal value of $\lambda$. Create plots of the cross-validation error as a function of $\lambda$. Report the resulting coefficient estimates, and discuss the results obtained. 
  
  (f)
  Now generate a response vector $Y$ according to the model
  $Y = \beta_{0} + \beta_{7}X^{7} + \epsilon$,
  and perform best subset selection and the lasso. Discuss the results obtained. 
  
### Problem 9
In this exercise, we will predict the number of applications received using the other variables in the `College` data set. 

  (a)
  Split the data set into a training set and a test set.
  
  (b)
  Fit a linear model using least squares on the training set, and report the test error obtained. 
  (c)
  Fit a ridge regression model on the training set, with $\lambda$ chosen by cross-validation. Report the test error obtained. 
  
  (d)
  Fit a lasso model on the training set, with $\lambda$ chosen by cross-validation. Report the test error obtained, along with the number of non-zero coefficient estimates. 
  
  (e)
  Fit a $PCR$ model on the training set, with $M$ chosen by cross-validation. Report the test error obtained, along with the value of $M$ selected by cross-validation. 
  
  (f)
  Fit a $PLS$ model on the training set, with $M$ chosen by cross-validation. Report the test error obtained, along with the value of $M$ selected by cross-validation. 
  
  (g)
  Comment on the results obtained. How accurately can we predict the number of college applications received? Is there much difference among the test errors resulting from these five approaches?
  
### Problem 10
We have seen that as the number of features used in a model increases, the training error will necessarily decrease, but the test error may not. We will now explore this in a simulated data set. 

  (a)
  Generate a data set with $p = 20$ features, $n = 1,000$ observations, and an associated quantitative response vector generated according to the model
  $Y = X\beta + \epsilon$,
  where $\beta$ has some elements that are exactly equal to zero. 
  
  (b)
  Split your data set into a training set containing $100$ observations and a test set containing $900$ observations. 
  
  (c)
  Perform best subset selection on the training set, and plot the training set $MSE$ associated with the best model of each size.
  
  (d)
  Plot the test set $MSE$ associated with the best model of each size.
  
  (e)
  For which model size does the test set $MSE$ take on its minimum value? Comment on your results. If it takes on its minimum value for a model containing only an intercept or a model containing all of the features, then play around with the way that you are generating the data in (a) until you come up with a scenario in which the test set $MSE$ is minimized for an intermediate model size.
  
  (f)
  How does the model at which the test set $MSE$ is minimized compared to the true model used to generate the data? Comment on the coefficient values. 
  
  (g)
  Create a plot displaying $\sqrt{\sum_{j=1}^{p}(\beta_{j}-\hat{\beta_{j}^{r}})^{2}}$ for a range of values of $r$, where $\hat{\beta_{j}^{r}}$ is the $j$th coefficient estimate for the best model containing $r$ coefficients. Comment on what you observe. How does this compare to the test $MSE$ plot from (d)?
  
### Problem 11
We will now try to predict per capita crime rate in the `Boston` data set. 

  (a)
  Try out some of the regression methods explored in this chapter, such as best subset selection, the lasso, ridge regression, and $PCR$. Present and discuss results for the approaches that you consider. 
  
  (b)
  Propose a model (or set of models) that seem to perform well on this data set, and justify your answer. Make sure that you are evaluating model performance using validation set error, cross-validation, or some other reasonable alternative, as opposed to using training error. 
  
  (c)
  Does your chosen model involve all of the features in the data set? Why or why not?

  