---
title: "solutioins to the applied exercises in islr2 ch11"
author: "Wenwen Kong"
date: "9/5/2022"
output:
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 10
This exercise focuses on the brain tumor data, which is included in the `ISLR2 R` library.

  (a)
  Plot the Kaplan-Meier survival curve with $\pm 1$ standard error bands, using the `survfit()` function in the `survival` package.
  
  (b)
  Draw a bootstrap sample of size $n = 88$ from the pairs $(y_{i}, \delta_{i})$, and compute the resulting Kaplan-Meier survival curve. Repeat this process $B = 200$ times. Use the results to obtain an estimate of the standard error of the Kaplan-Meier survival curve at each timepoint. Compare this to the standard error obtained in (a). 
  
  (c)
  Fit a Cox proportional hazards model that uses all of the predictors to predict survival. Summarize the main findings. 
  
  (d)
  Stratify the data by the value of `ki`. (Since only one observation has `ki = 40`, you can group that observation together with the observations that have `ki = 60`.) Plot Kaplan-Meier survival curves for each of the five strata, adjusted for the other predictors. 
  
### Problem 11
This example makes use of the data in Table 11.4

  (a)
  Create two groups of observations. In Group 1, $X \lt 2$, whereas in Group 2, $X \ge 2$. Plot the Kaplan-Meier survival curves corresponding to the two groups. Be sure to label the curves so that it is clear which curve corresponds to which group. By eye, does there appear to be a difference between the two groups' survival curves?
  
  (b)
  Fit Cox's proportional hazards model, using the group indicator as a covariate. What is the estimated coefficient? Write a sentence providing the interpretation of this coefficient, in terms of the hazard or the instantaneous probability of the event. Is there evidence that the true coefficient value is non-zero?
  
  (c)
  Recall from Section 11.5.2 that in the case of a single binary covariate, the log-rank test statistic shoiuld be identical to the score statistic for the Cox model. Conduct a log-rank test to determine whether there is a difference between the survival curves for the two groups. How does the $p$-value for the log-rank test statistic compare to the $p$-value for the score statistic for the Cox model from (b)?

